FROM alpine:latest
MAINTAINER Lars Olzem <hackebein@gmail.com>

ENV LD_LIBRARY_PATH=.:./redist

RUN apk add --update --no-cache \
		bash \
		libstdc++ \
		busybox-extras \
		expect

VOLUME \
    /app/files \
    /app/ts3server.sqlitedb \
    /app/ts3server.sqlitedb-shm \
    /app/ts3server.sqlitedb-wal

WORKDIR /app
USER 1000:1000
EXPOSE 9987/udp 30033 10011
ENTRYPOINT ["/app/ts3server_startscript.sh"]
