#!/bin/bash
set -eux

echo "[***] pre_build is running"

cd "$(dirname "$(readlink -f "$0")")"
cd ..

touch "$(pwd)/docker-compose.yml"
docker run --rm -v "$(pwd)/docker-compose.yml:/usr/src/app/docker-compose.yml" hackebein/docker-compose-builder-ts3server "hackebein/ts3server" "." "linux_alpine" "linux_amd64"
