FROM alpine:latest as base
RUN apk add --update --no-cache \
        tar \
        wget \
 && mkdir -p /app
ARG TS3SERVER_URL
ARG TS3SERVER_ARCHIVE
RUN wget --no-verbose "${TS3SERVER_URL}" -O "/tmp/${TS3SERVER_ARCHIVE}" \
 && tar -C /app --strip 1 -xf "/tmp/${TS3SERVER_ARCHIVE}"
COPY . /app
RUN chmod ug+x /app/start.sh \
 && rm -rf \
        /app/CHANGELOG \
        /app/doc \
        /app/docs \
        /app/tsdns \
        /app/ts3server_*.sh

FROM ubuntu:latest
MAINTAINER Lars Olzem <hackebein@gmail.com>
RUN apt update \
 && apt install -y \
        ca-certificates \
        expect \
 && apt upgrade -y \
 && apt clean \
 && rm -rf \
        /var/lib/apt/lists/*
ARG TS3SERVER_VERSION
ENV TS3SERVER_VERSION="$TS3SERVER_VERSION" \
    TS3SERVER_PLATFORM="linux_i386" \
    LD_LIBRARY_PATH=".:./redist" \
    LANG="C.UTF-8" \
    LC_ALL="C.UTF-8"
COPY --from=base /app /app
WORKDIR /app
EXPOSE 9987/udp 30033 10011 10022
ENTRYPOINT ["/app/start.sh"]
