name: "Trigger build at Docker Hub"

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  trigger:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies 
      run: |
        apt update
        apt install -y curl
    - name: Trigger Build
      run: |
        curl -X POST ${{ secrets.DOCKER_HUB_BUILD_TRIGGER_URL }}
