name: "default"
on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '8' # TODO: update to 14 (LTS)
      - name: Install npm packages
        run: npm install --prefix docker-compose_builder
      - name: Build docker-compose.yml
        # TODO: do all possible containers
        # run: npm start "../docker-compose.yml" "${{ github.repository }}" "." "freebsd_amd64" "freebsd_x86" "linux_alpine" "linux_amd64" "linux_x86" "mac" "win32" "win64"
        run: npm start --prefix docker-compose_builder "../docker-compose.yml" "${{ github.repository }}" "." "linux_alpine" "linux_amd64"
      - name: Build container images
        run: docker-compose build
      - name: Remove untagged container images
        run: "docker rmi $(docker images | grep '^<none>' | awk '{print $3}')"
      - name: Install container-diff
        run: |
          sudo curl -sL https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64 -o /usr/local/bin/container-diff
          sudo chmod +x /usr/local/bin/container-diff
      - name: Publish changed Images
        run: |
          DOCKER_REPO_RELATIVE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          for DOCKER_TAG in $(docker images --format '{{.Tag}}' "${DOCKER_REPO_RELATIVE}:*"); do
            IMAGE_NAME_RELATIVE=${DOCKER_REPO_RELATIVE}:${DOCKER_TAG}
            echo "[***] Compare ${IMAGE_NAME_RELATIVE} images ..."
            IMAGE_DIFFS=$(container-diff diff -n daemon://${IMAGE_NAME_RELATIVE} remote://${IMAGE_NAME_RELATIVE} --type=file --json | jq '.')
            IMAGE_DIFFS_COUNT=$(echo "${IMAGE_DIFFS}" | jq '[] + .[0].Diff.Adds + .[0].Diff.Dels + .[0].Diff.Mods | map(select(.Name | test("^(?:(?!\/var\/(?:log|cache)\/).)*$"))) | length')
            if [[ "${IMAGE_DIFFS_COUNT}" != "0" ]]; then
              echo "[***] Found diff: $(echo "${IMAGE_DIFFS}" | jq -cM '[] + .[0].Diff.Adds + .[0].Diff.Dels + .[0].Diff.Mods | map(select(.Name | test("^(?:(?!\/var\/(?:log|cache)\/).)*$")))')"
              echo "[***] Pushing ${IMAGE_NAME_RELATIVE} ..."
              docker push "${IMAGE_NAME_RELATIVE}"
            fi
          done
